// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxPUSfnMcAhmW38yxUJUEvHv8SrLP4y6k',
    appId: '1:489204131538:web:9b55d5eecf08f82a11ef0b',
    messagingSenderId: '489204131538',
    projectId: 'tezda-ce907',
    authDomain: 'tezda-ce907.firebaseapp.com',
    storageBucket: 'tezda-ce907.appspot.com',
    measurementId: 'G-JXLH122EYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAODKR1_MzVhk3OJ8edRe0c0b9HiRfyJfg',
    appId: '1:489204131538:android:f37ce6eb614e14e511ef0b',
    messagingSenderId: '489204131538',
    projectId: 'tezda-ce907',
    storageBucket: 'tezda-ce907.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzzecqxURF5YdxhDX3OeRwNE0M1vBT2-s',
    appId: '1:489204131538:ios:f6502e73e2049dfe11ef0b',
    messagingSenderId: '489204131538',
    projectId: 'tezda-ce907',
    storageBucket: 'tezda-ce907.appspot.com',
    androidClientId: '489204131538-h8ri5ojds20vmovs00cqpji2rntklaqo.apps.googleusercontent.com',
    iosClientId: '489204131538-u385ifh2bkns7aho31pfnc28ik70u8g9.apps.googleusercontent.com',
    iosBundleId: 'com.tezda.tezdaTask',
  );

}